INSERT OR REPLACE INTO cms_assets
(id, tenant_id, asset_key, asset_type, label, url, alt_text, source_provider, usage_context, status, metadata_json)
VALUES
('asset_animal_2cute','tenant_companionscpas','animal_2cute','image','Two Cute Dogs','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/2cute.webp','Two rescued dogs together','static','animal_profile','active','{"exclude_from_people":true}'),
('asset_animal_awwmaaann','tenant_companionscpas','animal_awwmaaann','image','Aww Maaann','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/awwmaaann-(1).webp','Rescue dog portrait','static','animal_profile','active','{}'),
('asset_animal_bigsmiles','tenant_companionscpas','animal_bigsmiles','image','Big Smiles','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/bigsmiles.webp','Happy rescue dog smiling','static','animal_profile','active','{}'),
('asset_animal_bluepit','tenant_companionscpas','animal_bluepit','image','Blue Pit','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/bluepit.webp','Smiling blue pit rescue dog','static','animal_profile','active','{}'),
('asset_animal_brindle','tenant_companionscpas','animal_brindle','image','Brindle','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/brindle.jpg','Brindle rescue dog','static','animal_profile','active','{}'),
('asset_animal_conehead','tenant_companionscpas','animal_conehead','image','Conehead Recovery','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/conehead.webp','Dog recovering after treatment with cone','static','animal_profile','active','{"campaign":"transport"}'),
('asset_animal_gimmieabite','tenant_companionscpas','animal_gimmieabite','image','Gimmie A Bite','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/gimmieabite.webp','Rescue dog looking at food','static','animal_profile','active','{}'),
('asset_animal_goinhome','tenant_companionscpas','animal_goinhome','image','Going Home','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/goinhome.webp','Adopted dog going home','static','adoption_story','active','{}'),
('asset_animal_happyboy','tenant_companionscpas','animal_happyboy','image','Happy Boy','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/happyboy.webp','Happy rescue dog','static','animal_profile','active','{}'),
('asset_animal_hungryboy','tenant_companionscpas','animal_hungryboy','image','Hungry Boy','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/hungryboy.webp','Rescue dog needing care','static','animal_profile','active','{}'),
('asset_animal_miniscoobydoo','tenant_companionscpas','animal_miniscoobydoo','image','Mini Scooby Doo','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/miniscoobydoo.webp','Small rescued dog recovering','static','animal_profile','active','{}'),
('asset_animal_pup','tenant_companionscpas','animal_pup','image','Pup','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/pup.webp','Young puppy looking up','static','animal_profile','active','{}'),
('asset_animal_redeye','tenant_companionscpas','animal_redeye','image','Red Eye','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/redeye.webp','Rescue dog portrait','static','animal_profile','active','{}'),
('asset_animal_skinnyman','tenant_companionscpas','animal_skinnyman','image','Skinny Man','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/skinnyman.webp','Malnourished rescued dog needing support','static','animal_profile','active','{"campaign":"medical"}'),
('asset_animal_sus','tenant_companionscpas','animal_sus','image','Mischief Face','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/sus.webp','Silly mischievous rescue dog','static','animal_profile','active','{}'),
('asset_animal_thinboy','tenant_companionscpas','animal_thinboy','image','Thin Boy Medical Support','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/thinboy.webp','Malnourished dog receiving care','static','animal_profile','active','{"campaign":"medical"}'),
('asset_animal_thisismysweater','tenant_companionscpas','animal_thisismysweater','image','This Is My Sweater','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/thisismysweater.webp','Rescue dog wearing sweater','static','animal_profile','active','{}'),
('asset_animal_upclose','tenant_companionscpas','animal_upclose','image','Up Close Hero Dog','https://companionscpas-platform.samprimeauxwork.workers.dev/assets/animals/upclose.webp','Happy rescued dog close up','static','hero','active','{}');
